version: '3'
services:
  # api-ufc:
  #   build: .
  #   container_name: "api-ufc"
  #   volumes:
  #     - ./:/usr/src/app
  #     - nodemodules_api:/usr/src/app/node_modules
  #   ports:
  #     - "80:80"
  #   restart: on-failure
  #   networks:
  #     - private
  redis:
    container_name: api-ufc-redis
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  nodemodules: {}
  nodemodules_api: {}

networks:
  private:
  custom:
    name: jobs
    driver: bridge